### ISSUE TITLE
Is there a way to turn off auto-update or heartbeat feature?

### ISSUE THREAD

**Issue by lamalediction** [andryou/Decreased-Productivity#3]
Hello, 
I was told my computer generated "suspicious traffic" by the network administrator. It stopped when I deleted Decreased Productivity and returned when I reinstalled it. I know this is not at all a scientific way to prove that the extension is responsible but this all I have so far. I'm not sure what they mean by suspicious activity.
Is there some kind of heartbeat function that could explain it? Could it be caused by the auto-update function? If so, can it be turned off?

**Comment by andryou** [comment]
Hi, the only type of heartbeat (or check) is the one to check if there are any updates for DP on the Chrome Web Store; there are no rogue connections being made and all the code is available for review and scrutiny here on Github.

AFAIK, this cannot be turned off but you can choose to download this repository and load it as an unpacked extension in Chrome.

I hope this helps.
