### ISSUE TITLE
Decreased Productivity doesn't work with WhatsAppWeb

### ISSUE THREAD

**Issue by Asator** [andryou/Decreased-Productivity#5]
Hi,
first thanks for your cool tool!
Since today morning, Decreased-Productivity does not work properly with WhatsAppWeb anymore which is actually the biggest use case of Decreased-Productivity for my friends and me. 
Issue:
The problem is that whenevery turning DP on when being on web.whatsapp.com while being logged in, the screen becomes a plain, white screen. 
![image](https://user-images.githubusercontent.com/4682869/33562571-e1ea1ac8-d915-11e7-836e-df12e1ae1091.png)
As long as you are not logged in, everything looks like before, but as soon as you scan the QR-Code, the entire screen looks like above.

The bug appeared for my friends and me independently this morning, probably with a changes on the site web.whatsapp.com. I tested this behaviour on multiple machines and can confirm that it appears on every machine in different screen resolutions. 

It would be great if this could be fixed as it is (like said before) our main use case - as well as for probably a lot of others.

**Comment by andryou** [comment]
Thanks for the report, I will look into this asap. Side-note: I'll also be looking into creating a Firefox build :)

**Comment by Asator** [comment]
Thank you, sounds cool!

**Comment by andryou** [comment]
Should be fixed in v0.46.56.10 which I've just pushed! Please give it a try and let me know if it fixes Whatsapp Web for you.

And DP is now on Firefox: https://addons.mozilla.org/en-US/firefox/addon/decreased-productivity-andryou/

**Comment by Asator** [comment]
wow, that was fast, well done & thanks a lot!
There is one tiny issue left, if you try to send pictures, you don't see that you are trying to send a picture, so no sending preview appears, you simply keep viewing the chat. But as the important stuff is working again, I'll close this issue. Thanks again!
